// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	entity "github.com/emgeorrk/wrtgram/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// LookPath mocks base method.
func (m *MockRunner) LookPath(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookPath", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// LookPath indicates an expected call of LookPath.
func (mr *MockRunnerMockRecorder) LookPath(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookPath", reflect.TypeOf((*MockRunner)(nil).LookPath), name)
}

// Run mocks base method.
func (m *MockRunner) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockRunnerMockRecorder) Run(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRunner)(nil).Run), varargs...)
}

// RunInput mocks base method.
func (m *MockRunner) RunInput(ctx context.Context, stdin io.Reader, name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, stdin, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunInput", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunInput indicates an expected call of RunInput.
func (mr *MockRunnerMockRecorder) RunInput(ctx, stdin, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, stdin, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInput", reflect.TypeOf((*MockRunner)(nil).RunInput), varargs...)
}

// Stream mocks base method.
func (m *MockRunner) Stream(ctx context.Context, name string, args ...string) (<-chan string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Stream", varargs...)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockRunnerMockRecorder) Stream(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockRunner)(nil).Stream), varargs...)
}

// MockUbus is a mock of Ubus interface.
type MockUbus struct {
	ctrl     *gomock.Controller
	recorder *MockUbusMockRecorder
	isgomock struct{}
}

// MockUbusMockRecorder is the mock recorder for MockUbus.
type MockUbusMockRecorder struct {
	mock *MockUbus
}

// NewMockUbus creates a new mock instance.
func NewMockUbus(ctrl *gomock.Controller) *MockUbus {
	mock := &MockUbus{ctrl: ctrl}
	mock.recorder = &MockUbusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUbus) EXPECT() *MockUbusMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockUbus) Call(ctx context.Context, object, method string, args, out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, object, method, args, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockUbusMockRecorder) Call(ctx, object, method, args, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockUbus)(nil).Call), ctx, object, method, args, out)
}

// List mocks base method.
func (m *MockUbus) List(ctx context.Context, pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUbusMockRecorder) List(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUbus)(nil).List), ctx, pattern)
}

// MockUCI is a mock of UCI interface.
type MockUCI struct {
	ctrl     *gomock.Controller
	recorder *MockUCIMockRecorder
	isgomock struct{}
}

// MockUCIMockRecorder is the mock recorder for MockUCI.
type MockUCIMockRecorder struct {
	mock *MockUCI
}

// NewMockUCI creates a new mock instance.
func NewMockUCI(ctrl *gomock.Controller) *MockUCI {
	mock := &MockUCI{ctrl: ctrl}
	mock.recorder = &MockUCIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUCI) EXPECT() *MockUCIMockRecorder {
	return m.recorder
}

// AddAnonymous mocks base method.
func (m *MockUCI) AddAnonymous(ctx context.Context, pkg, typ string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnonymous", ctx, pkg, typ)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAnonymous indicates an expected call of AddAnonymous.
func (mr *MockUCIMockRecorder) AddAnonymous(ctx, pkg, typ any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnonymous", reflect.TypeOf((*MockUCI)(nil).AddAnonymous), ctx, pkg, typ)
}

// AddSection mocks base method.
func (m *MockUCI) AddSection(ctx context.Context, pkg, typ, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSection", ctx, pkg, typ, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSection indicates an expected call of AddSection.
func (mr *MockUCIMockRecorder) AddSection(ctx, pkg, typ, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSection", reflect.TypeOf((*MockUCI)(nil).AddSection), ctx, pkg, typ, name)
}

// Commit mocks base method.
func (m *MockUCI) Commit(ctx context.Context, pkg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, pkg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockUCIMockRecorder) Commit(ctx, pkg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockUCI)(nil).Commit), ctx, pkg)
}

// Delete mocks base method.
func (m *MockUCI) Delete(ctx context.Context, pkg, section string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, pkg, section)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUCIMockRecorder) Delete(ctx, pkg, section any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUCI)(nil).Delete), ctx, pkg, section)
}

// Get mocks base method.
func (m *MockUCI) Get(ctx context.Context, pkg string) (entity.UCIPackage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pkg)
	ret0, _ := ret[0].(entity.UCIPackage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUCIMockRecorder) Get(ctx, pkg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUCI)(nil).Get), ctx, pkg)
}

// Set mocks base method.
func (m *MockUCI) Set(ctx context.Context, pkg, section string, values map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, pkg, section, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockUCIMockRecorder) Set(ctx, pkg, section, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockUCI)(nil).Set), ctx, pkg, section, values)
}

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *MockSender) AnswerCallback(ctx context.Context, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MockSenderMockRecorder) AnswerCallback(ctx, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*MockSender)(nil).AnswerCallback), ctx, callbackID, text)
}

// ChatAction mocks base method.
func (m *MockSender) ChatAction(ctx context.Context, chatID int64, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatAction", ctx, chatID, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatAction indicates an expected call of ChatAction.
func (mr *MockSenderMockRecorder) ChatAction(ctx, chatID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatAction", reflect.TypeOf((*MockSender)(nil).ChatAction), ctx, chatID, action)
}

// EditMessage mocks base method.
func (m *MockSender) EditMessage(ctx context.Context, chatID int64, messageID int, msg entity.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessage", ctx, chatID, messageID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockSenderMockRecorder) EditMessage(ctx, chatID, messageID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockSender)(nil).EditMessage), ctx, chatID, messageID, msg)
}

// Me mocks base method.
func (m *MockSender) Me(ctx context.Context) (entity.BotInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx)
	ret0, _ := ret[0].(entity.BotInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockSenderMockRecorder) Me(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockSender)(nil).Me), ctx)
}

// SendDocument mocks base method.
func (m *MockSender) SendDocument(ctx context.Context, chatID int64, doc entity.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDocument", ctx, chatID, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDocument indicates an expected call of SendDocument.
func (mr *MockSenderMockRecorder) SendDocument(ctx, chatID, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDocument", reflect.TypeOf((*MockSender)(nil).SendDocument), ctx, chatID, doc)
}

// SendMessage mocks base method.
func (m *MockSender) SendMessage(ctx context.Context, chatID int64, msg entity.Message) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, msg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockSenderMockRecorder) SendMessage(ctx, chatID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockSender)(nil).SendMessage), ctx, chatID, msg)
}

// SetCommands mocks base method.
func (m *MockSender) SetCommands(ctx context.Context, cmds []entity.BotCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCommands", ctx, cmds)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCommands indicates an expected call of SetCommands.
func (mr *MockSenderMockRecorder) SetCommands(ctx, cmds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCommands", reflect.TypeOf((*MockSender)(nil).SetCommands), ctx, cmds)
}

// MockUpdateSource is a mock of UpdateSource interface.
type MockUpdateSource struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSourceMockRecorder
	isgomock struct{}
}

// MockUpdateSourceMockRecorder is the mock recorder for MockUpdateSource.
type MockUpdateSourceMockRecorder struct {
	mock *MockUpdateSource
}

// NewMockUpdateSource creates a new mock instance.
func NewMockUpdateSource(ctrl *gomock.Controller) *MockUpdateSource {
	mock := &MockUpdateSource{ctrl: ctrl}
	mock.recorder = &MockUpdateSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateSource) EXPECT() *MockUpdateSourceMockRecorder {
	return m.recorder
}

// Updates mocks base method.
func (m *MockUpdateSource) Updates(ctx context.Context) <-chan entity.Update {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx)
	ret0, _ := ret[0].(<-chan entity.Update)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockUpdateSourceMockRecorder) Updates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockUpdateSource)(nil).Updates), ctx)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// After mocks base method.
func (m *MockClock) After(d time.Duration) <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "After", d)
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// After indicates an expected call of After.
func (mr *MockClockMockRecorder) After(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "After", reflect.TypeOf((*MockClock)(nil).After), d)
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockPinger is a mock of Pinger interface.
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *MockPingerMockRecorder
	isgomock struct{}
}

// MockPingerMockRecorder is the mock recorder for MockPinger.
type MockPingerMockRecorder struct {
	mock *MockPinger
}

// NewMockPinger creates a new mock instance.
func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &MockPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinger) EXPECT() *MockPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockPinger) Ping(ctx context.Context, dev, target string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, dev, target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPingerMockRecorder) Ping(ctx, dev, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPinger)(nil).Ping), ctx, dev, target)
}

// MockRouter is a mock of Router interface.
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
	isgomock struct{}
}

// MockRouterMockRecorder is the mock recorder for MockRouter.
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance.
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// ClearDefault mocks base method.
func (m *MockRouter) ClearDefault(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDefault", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDefault indicates an expected call of ClearDefault.
func (mr *MockRouterMockRecorder) ClearDefault(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDefault", reflect.TypeOf((*MockRouter)(nil).ClearDefault), ctx)
}

// DefaultDev mocks base method.
func (m *MockRouter) DefaultDev(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultDev", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DefaultDev indicates an expected call of DefaultDev.
func (mr *MockRouterMockRecorder) DefaultDev(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultDev", reflect.TypeOf((*MockRouter)(nil).DefaultDev), ctx)
}

// DeleteNets mocks base method.
func (m *MockRouter) DeleteNets(ctx context.Context, nets []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNets", ctx, nets)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNets indicates an expected call of DeleteNets.
func (mr *MockRouterMockRecorder) DeleteNets(ctx, nets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNets", reflect.TypeOf((*MockRouter)(nil).DeleteNets), ctx, nets)
}

// EnsureNTPDirect mocks base method.
func (m *MockRouter) EnsureNTPDirect(ctx context.Context, gw, dev string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNTPDirect", ctx, gw, dev)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureNTPDirect indicates an expected call of EnsureNTPDirect.
func (mr *MockRouterMockRecorder) EnsureNTPDirect(ctx, gw, dev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNTPDirect", reflect.TypeOf((*MockRouter)(nil).EnsureNTPDirect), ctx, gw, dev)
}

// ReplaceNets mocks base method.
func (m *MockRouter) ReplaceNets(ctx context.Context, nets []string, dev string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceNets", ctx, nets, dev)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceNets indicates an expected call of ReplaceNets.
func (mr *MockRouterMockRecorder) ReplaceNets(ctx, nets, dev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceNets", reflect.TypeOf((*MockRouter)(nil).ReplaceNets), ctx, nets, dev)
}

// SetDefault mocks base method.
func (m *MockRouter) SetDefault(ctx context.Context, dev string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefault", ctx, dev)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefault indicates an expected call of SetDefault.
func (mr *MockRouterMockRecorder) SetDefault(ctx, dev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefault", reflect.TypeOf((*MockRouter)(nil).SetDefault), ctx, dev)
}

// MockWAN is a mock of WAN interface.
type MockWAN struct {
	ctrl     *gomock.Controller
	recorder *MockWANMockRecorder
	isgomock struct{}
}

// MockWANMockRecorder is the mock recorder for MockWAN.
type MockWANMockRecorder struct {
	mock *MockWAN
}

// NewMockWAN creates a new mock instance.
func NewMockWAN(ctrl *gomock.Controller) *MockWAN {
	mock := &MockWAN{ctrl: ctrl}
	mock.recorder = &MockWANMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWAN) EXPECT() *MockWANMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockWAN) Status(ctx context.Context) (entity.WANStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(entity.WANStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockWANMockRecorder) Status(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockWAN)(nil).Status), ctx)
}

// MockTunnels is a mock of Tunnels interface.
type MockTunnels struct {
	ctrl     *gomock.Controller
	recorder *MockTunnelsMockRecorder
	isgomock struct{}
}

// MockTunnelsMockRecorder is the mock recorder for MockTunnels.
type MockTunnelsMockRecorder struct {
	mock *MockTunnels
}

// NewMockTunnels creates a new mock instance.
func NewMockTunnels(ctrl *gomock.Controller) *MockTunnels {
	mock := &MockTunnels{ctrl: ctrl}
	mock.recorder = &MockTunnelsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTunnels) EXPECT() *MockTunnelsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTunnels) List(ctx context.Context) ([]entity.TunnelRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.TunnelRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTunnelsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTunnels)(nil).List), ctx)
}

// Status mocks base method.
func (m *MockTunnels) Status(ctx context.Context, ref entity.TunnelRef) (entity.Tunnel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, ref)
	ret0, _ := ret[0].(entity.Tunnel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockTunnelsMockRecorder) Status(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockTunnels)(nil).Status), ctx, ref)
}

// MockLeases is a mock of Leases interface.
type MockLeases struct {
	ctrl     *gomock.Controller
	recorder *MockLeasesMockRecorder
	isgomock struct{}
}

// MockLeasesMockRecorder is the mock recorder for MockLeases.
type MockLeasesMockRecorder struct {
	mock *MockLeases
}

// NewMockLeases creates a new mock instance.
func NewMockLeases(ctrl *gomock.Controller) *MockLeases {
	mock := &MockLeases{ctrl: ctrl}
	mock.recorder = &MockLeasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeases) EXPECT() *MockLeasesMockRecorder {
	return m.recorder
}

// Leases mocks base method.
func (m *MockLeases) Leases(ctx context.Context) ([]entity.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leases", ctx)
	ret0, _ := ret[0].([]entity.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leases indicates an expected call of Leases.
func (mr *MockLeasesMockRecorder) Leases(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leases", reflect.TypeOf((*MockLeases)(nil).Leases), ctx)
}

// MockWireless is a mock of Wireless interface.
type MockWireless struct {
	ctrl     *gomock.Controller
	recorder *MockWirelessMockRecorder
	isgomock struct{}
}

// MockWirelessMockRecorder is the mock recorder for MockWireless.
type MockWirelessMockRecorder struct {
	mock *MockWireless
}

// NewMockWireless creates a new mock instance.
func NewMockWireless(ctrl *gomock.Controller) *MockWireless {
	mock := &MockWireless{ctrl: ctrl}
	mock.recorder = &MockWirelessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWireless) EXPECT() *MockWirelessMockRecorder {
	return m.recorder
}

// Clients mocks base method.
func (m *MockWireless) Clients(ctx context.Context) ([]entity.WifiClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clients", ctx)
	ret0, _ := ret[0].([]entity.WifiClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clients indicates an expected call of Clients.
func (mr *MockWirelessMockRecorder) Clients(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clients", reflect.TypeOf((*MockWireless)(nil).Clients), ctx)
}

// MockHostHints is a mock of HostHints interface.
type MockHostHints struct {
	ctrl     *gomock.Controller
	recorder *MockHostHintsMockRecorder
	isgomock struct{}
}

// MockHostHintsMockRecorder is the mock recorder for MockHostHints.
type MockHostHintsMockRecorder struct {
	mock *MockHostHints
}

// NewMockHostHints creates a new mock instance.
func NewMockHostHints(ctrl *gomock.Controller) *MockHostHints {
	mock := &MockHostHints{ctrl: ctrl}
	mock.recorder = &MockHostHintsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostHints) EXPECT() *MockHostHintsMockRecorder {
	return m.recorder
}

// Hints mocks base method.
func (m *MockHostHints) Hints(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hints", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hints indicates an expected call of Hints.
func (mr *MockHostHintsMockRecorder) Hints(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hints", reflect.TypeOf((*MockHostHints)(nil).Hints), ctx)
}

// MockBackuper is a mock of Backuper interface.
type MockBackuper struct {
	ctrl     *gomock.Controller
	recorder *MockBackuperMockRecorder
	isgomock struct{}
}

// MockBackuperMockRecorder is the mock recorder for MockBackuper.
type MockBackuperMockRecorder struct {
	mock *MockBackuper
}

// NewMockBackuper creates a new mock instance.
func NewMockBackuper(ctrl *gomock.Controller) *MockBackuper {
	mock := &MockBackuper{ctrl: ctrl}
	mock.recorder = &MockBackuperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackuper) EXPECT() *MockBackuperMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockBackuper) Backup(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Backup indicates an expected call of Backup.
func (mr *MockBackuperMockRecorder) Backup(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockBackuper)(nil).Backup), ctx, path)
}

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
	isgomock struct{}
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockStateStore) Load(name string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", name, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockStateStoreMockRecorder) Load(name, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStateStore)(nil).Load), name, v)
}

// Save mocks base method.
func (m *MockStateStore) Save(name string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", name, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStateStoreMockRecorder) Save(name, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStateStore)(nil).Save), name, v)
}

// MockLogSource is a mock of LogSource interface.
type MockLogSource struct {
	ctrl     *gomock.Controller
	recorder *MockLogSourceMockRecorder
	isgomock struct{}
}

// MockLogSourceMockRecorder is the mock recorder for MockLogSource.
type MockLogSourceMockRecorder struct {
	mock *MockLogSource
}

// NewMockLogSource creates a new mock instance.
func NewMockLogSource(ctrl *gomock.Controller) *MockLogSource {
	mock := &MockLogSource{ctrl: ctrl}
	mock.recorder = &MockLogSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogSource) EXPECT() *MockLogSourceMockRecorder {
	return m.recorder
}

// Tail mocks base method.
func (m *MockLogSource) Tail(ctx context.Context) (<-chan entity.LogLine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tail", ctx)
	ret0, _ := ret[0].(<-chan entity.LogLine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tail indicates an expected call of Tail.
func (mr *MockLogSourceMockRecorder) Tail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tail", reflect.TypeOf((*MockLogSource)(nil).Tail), ctx)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotifier) Notify(ctx context.Context, msg entity.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify", ctx, msg)
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifierMockRecorder) Notify(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifier)(nil).Notify), ctx, msg)
}

// NotifyDocument mocks base method.
func (m *MockNotifier) NotifyDocument(ctx context.Context, doc entity.Document) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyDocument", ctx, doc)
}

// NotifyDocument indicates an expected call of NotifyDocument.
func (mr *MockNotifierMockRecorder) NotifyDocument(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyDocument", reflect.TypeOf((*MockNotifier)(nil).NotifyDocument), ctx, doc)
}
